source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "rack-cors"
gem "httparty"
gem "jwt"

group :development, :test do
  gem "byebug"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "dotenv-rails"
  gem "rspec-rails"
  gem "factory_bot_rails"
end

group :test do
  gem "simplecov", require: false
end
